import os

TOKEN="HF_TOKEN"
HUGGINGFACE_REPO_ID_NAME="HUGGINGFACE_REPO_ID"
HF_TOKEN=os.environ.get(TOKEN)

HUGGINGFACE_REPO_ID=os.environ.get(HUGGINGFACE_REPO_ID_NAME)
DB_FAISS_PATH="vectorstore/db_faiss"
DATA_PATH="data/"
CHUNK_SIZE=500
CHUNK_OVERLAP=50